os:
  - linux
  - osx
dist: bionic
group: stable
language: cpp
addons:
  apt:
    packages:
      - cmake
      - cmake-data
      - freeglut3-dev
      - g++-5
      - gcc-5
      - libglew-dev
      - liblua5.1-dev
      - libopenal-dev
      - libphysfs-dev
      - libsdl2-dev
      - libsdl2-image-dev
      - libtinyxml-dev
      - libvorbis-dev
      - libxi-dev
  homebrew:
    update: true
    packages:
      - glew
      - physfs
      - sdl2
      - sdl2_image
      - lua51
      - tinyxml
      - libvorbis
      - libogg
script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX=g++-5; export CC=gcc-5; fi
  - ./build.sh
