os: linux
dist: trusty
group: stable
language: cpp
addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - cmake-data
      - freeglut3-dev
      - g++-5
      - gcc-5
      - libglew-dev
      - liblua5.1-dev
      - libopenal-dev
      - libphysfs-dev
      - libsdl-image1.2-dev
      - libsdl-net1.2-dev
      - libsdl-ttf2.0-dev
      - libtinyxml-dev
      - libvorbis-dev
      - libxi-dev
script:
  - export CXX=g++-5
  - export CC=gcc-5
  - ./build.sh
